# ===================================================================
# DEV / LOCAL PROFILE
# ===================================================================
server.port=8080

# Local PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/money_reminder_db
spring.datasource.username=postgres
spring.datasource.password=naveen
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Dev Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
